services:
  postgres:
    image: postgres:latest
    container_name: lithium-db
    environment:
      POSTGRES_DB: lithium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - lithium-network

  backend:
    image: phillychi3/lithium-player-backend:latest
    container_name: lithium-backend
    volumes:
      - backend:/app/data
    ports:
      - "8000:8000"
    environment:
      SQLIP: postgres
    networks:
      - lithium-network
    depends_on:
      - postgres

  frontend:
    image: phillychi3/lithium-player-frontend:latest
    container_name: lithium-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - lithium-network
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    container_name: lithium-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "4000:80"
    networks:
      - lithium-network
    depends_on:
      - frontend

volumes:
  postgres_data:
  backend:

networks:
  lithium-network:
    driver: bridge
